### ISSUE TITLE
compile failed - mac.c:1543:12: error: static declaration of ‘ath10k_recalc_rtscts_prot’ follows non-static declaration

### ISSUE THREAD

**Issue by gsustek** [greearb/linux-ct-5.4#1]
Compile of this kernel source on ubuntu 20.04 failed with exception:
gs@u1804:~/linux-ct-5.4$ make  LOCALVERSION=-regfix V=s
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  DESCEND  objtool
  CHK     include/generated/compile.h
  CC [M]  drivers/net/wireless/ath/ath10k/mac.o
drivers/net/wireless/ath/ath10k/mac.c: In function ‘chan_to_phymode’:
drivers/net/wireless/ath/ath10k/mac.c:685:3: warning: enumeration value ‘NL80211_CHAN_WIDTH_5_NOHT’ not handled in switch [-Wswitch]
  685 |   switch (chandef->width) {
      |   ^~~~~~
drivers/net/wireless/ath/ath10k/mac.c:685:3: warning: enumeration value ‘NL80211_CHAN_WIDTH_10_NOHT’ not handled in switch [-Wswitch]
drivers/net/wireless/ath/ath10k/mac.c:708:3: warning: enumeration value ‘NL80211_CHAN_WIDTH_5_NOHT’ not handled in switch [-Wswitch]
  708 |   switch (chandef->width) {
      |   ^~~~~~
drivers/net/wireless/ath/ath10k/mac.c:708:3: warning: enumeration value ‘NL80211_CHAN_WIDTH_10_NOHT’ not handled in switch [-Wswitch]
drivers/net/wireless/ath/ath10k/mac.c: In function ‘ath10k_mac_set_rts’:
drivers/net/wireless/ath/ath10k/mac.c:973:8: error: implicit declaration of function ‘ath10k_recalc_rtscts_prot’ [-Werror=implicit-function-declaration]
  973 |  ret = ath10k_recalc_rtscts_prot(arvif);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/wireless/ath/ath10k/mac.c: At top level:
drivers/net/wireless/ath/ath10k/mac.c:1543:12: error: static declaration of ‘ath10k_recalc_rtscts_prot’ follows non-static declaration
 1543 | static int ath10k_recalc_rtscts_prot(struct ath10k_vif *arvif)
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/wireless/ath/ath10k/mac.c:973:8: note: previous implicit declaration of ‘ath10k_recalc_rtscts_prot’ was here
  973 |  ret = ath10k_recalc_rtscts_prot(arvif);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:266: drivers/net/wireless/ath/ath10k/mac.o] Error 1
make[4]: *** [scripts/Makefile.build:500: drivers/net/wireless/ath/ath10k] Error 2
make[3]: *** [scripts/Makefile.build:500: drivers/net/wireless/ath] Error 2
make[2]: *** [scripts/Makefile.build:500: drivers/net/wireless] Error 2
make[1]: *** [scripts/Makefile.build:500: drivers/net] Error 2
make: *** [Makefile:1706: drivers] Error 2

**Comment by greearb** [comment]
Should be fixed now.
